/**
 * Скрипт для синхронизации .env файла между frontend и backend
 * Копирует переменные из корневого .env в соответствующие подпроекты
 */

const fs = require('fs');
const path = require('path');

const rootDir = path.resolve(__dirname, '..');
const backendDir = path.join(rootDir, 'backend');
const frontendDir = path.join(rootDir, 'frontend');
const rootEnvPath = path.join(rootDir, '.env');

// Цвета для консоли
const colors = {
  reset: '\x1b[0m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  red: '\x1b[31m',
  blue: '\x1b[34m'
};

function log(message, color = 'reset') {
  console.log(`${colors[color]}${message}${colors.reset}`);
}

function parseEnv(content) {
  const env = {};
  const lines = content.split('\n');
  
  for (const line of lines) {
    const trimmed = line.trim();
    
    // Пропускаем пустые строки и комментарии
    if (!trimmed || trimmed.startsWith('#')) continue;
    
    // Обрабатываем переменные
    const match = trimmed.match(/^([^=]+)=(.*)$/);
    if (match) {
      const key = match[1].trim();
      let value = match[2].trim();
      
      // Убираем кавычки если есть
      if ((value.startsWith('"') && value.endsWith('"')) ||
          (value.startsWith("'") && value.endsWith("'"))) {
        value = value.slice(1, -1);
      }
      
      env[key] = value;
    }
  }
  
  return env;
}

function expandVariables(env) {
  const expanded = { ...env };
  
  for (const [key, value] of Object.entries(expanded)) {
    expanded[key] = value.replace(/\$\{([^}]+)\}/g, (match, varName) => {
      return expanded[varName] || match;
    });
  }
  
  return expanded;
}

function generateBackendEnv(env) {
  const backendVars = [
    'NODE_ENV',
    'PORT',
    'BACKEND_URL',
    'DATABASE_URL',
    'REDIS_URL',
    'JWT_SECRET',
    'JWT_EXPIRES_IN',
    'ALLOWED_ORIGINS',
    'FRONTEND_URL',
    'AUTH_TYPE',
    'DISCORD_CLIENT_ID',
    'DISCORD_CLIENT_SECRET',
    'DISCORD_REDIRECT_URI',
    'DISCORD_BOT_TOKEN',
    'DISCORD_GUILD_ID',
    'DISCORD_LOG_CHANNEL_ID',
    'IPS_API_URL',
    'IPS_API_KEY',
    'IPS_CLIENT_ID',
    'IPS_CLIENT_SECRET',
    'IPS_REDIRECT_URI',
    'SMTP_HOST',
    'SMTP_PORT',
    'SMTP_USER',
    'SMTP_PASS',
    'SMTP_FROM',
    'MAX_FILE_SIZE',
    'UPLOAD_PATH',
    'LOG_LEVEL',
    'LOG_FILE',
    'RATE_LIMIT_WINDOW_MS',
    'RATE_LIMIT_MAX_REQUESTS',
    'SESSION_SECRET',
    'SESSION_MAX_AGE',
    'SSL_CERT_PATH',
    'SSL_KEY_PATH'
  ];
  
  let content = '# Backend Environment Variables\n';
  content += '# Auto-generated from root .env file\n';
  content += '# DO NOT EDIT THIS FILE DIRECTLY - Edit root .env instead\n\n';
  
  for (const varName of backendVars) {
    if (env[varName]) {
      const value = env[varName];
      // Если значение содержит пробелы или спецсимволы, оборачиваем в кавычки
      if (value.includes(' ') || value.includes('$') || value.includes('#')) {
        content += `${varName}="${value}"\n`;
      } else {
        content += `${varName}=${value}\n`;
      }
    }
  }
  
  return content;
}

function generateFrontendEnv(env) {
  const frontendVars = [
    'NODE_ENV',
    'NEXT_PUBLIC_BACKEND_URL',
    'NEXT_PUBLIC_API_URL',
    'FRONTEND_URL',
    'NEXT_PUBLIC_AUTH_TYPE',
    'NEXT_PUBLIC_DISCORD_CLIENT_ID',
    'NEXT_PUBLIC_DISCORD_REDIRECT_URI',
    'NEXT_PUBLIC_ENABLE_ANALYTICS',
    'NEXT_PUBLIC_ENABLE_ERROR_REPORTING',
    'NEXT_PUBLIC_GOOGLE_ANALYTICS_ID',
    'NEXT_PUBLIC_SENTRY_DSN',
    'NEXT_PUBLIC_MAP_API_KEY',
    'NEXT_TELEMETRY_DISABLED'
  ];
  
  let content = '# Frontend Environment Variables\n';
  content += '# Auto-generated from root .env file\n';
  content += '# DO NOT EDIT THIS FILE DIRECTLY - Edit root .env instead\n\n';
  
  for (const varName of frontendVars) {
    if (env[varName]) {
      const value = env[varName];
      // Если значение содержит пробелы или спецсимволы, оборачиваем в кавычки
      if (value.includes(' ') || value.includes('$') || value.includes('#')) {
        content += `${varName}="${value}"\n`;
      } else {
        content += `${varName}=${value}\n`;
      }
    }
  }
  
  return content;
}

function main() {
  log('🔄 Настройка .env файлов...', 'blue');
  
  // Проверяем наличие корневого .env
  if (!fs.existsSync(rootEnvPath)) {
    log('❌ Корневой .env файл не найден!', 'red');
    log('📄 Скопируйте .env.example в .env и настройте переменные', 'yellow');
    process.exit(1);
  }
  
  // Читаем корневой .env
  const rootEnvContent = fs.readFileSync(rootEnvPath, 'utf8');
  const env = expandVariables(parseEnv(rootEnvContent));
  
  log('✅ Корневой .env файл прочитан', 'green');
  
  // Генерируем backend .env
  const backendEnvContent = generateBackendEnv(env);
  fs.writeFileSync(path.join(backendDir, '.env'), backendEnvContent);
  log('✅ Backend .env создан', 'green');
  
  // Генерируем frontend .env.local
  const frontendEnvContent = generateFrontendEnv(env);
  fs.writeFileSync(path.join(frontendDir, '.env.local'), frontendEnvContent);
  log('✅ Frontend .env.local создан', 'green');
  
  log('\n📊 Переменные окружения синхронизированы!', 'green');
  log('📝 Для изменения настроек редактируйте корневой .env файл', 'yellow');
}

main();
